server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/amazon_product_db1
    username: root
    password: cscorner

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
